
#----------------------------------------------------------------------
#           SETTINGS FOR THE ELIOM PROJECT hack2020
#----------------------------------------------------------------------

PROJECT_NAME := hack2020

# Source files for the server
SERVER_FILES := $(wildcard *.eliomi *.eliom)
# Source files for the client
CLIENT_FILES := $(wildcard *.eliomi *.eliom)

# OCamlfind packages for the server
SERVER_PACKAGES := netsys netstring netclient xmlm humane_re
# OCamlfind packages for the client
CLIENT_PACKAGES :=

# Mobile configuration:
# Application ID
APPLICATION_ID := org.ocsigen.mobile
# Version of your mobile's application
APPLICATION_VERSION := 1.0
# Application description
APPLICATION_DESC := Hello world from eliom-distillery
# Author
AUTHOR_NAME := ocsigen team
# Author's website
AUTHOR_WEBSITE := ocsigen.org
# Author's mail
AUTHOR_MAIL := noreply@ocsigen.org

# The authorized urls for your mobile application
ACCESS_URL := \
	http://localhost \
	http://ocsigen.org

# The platforms to call for build, mobile-install, run and remove rules
PLATFORMS :=

# Use phonegap build (yes/no):
# Phonegap build allow to compile / install and run online.
USE_PHONEGAP_BUILD := no

# Directory with files to be statically served
LOCAL_STATIC = static

# The backend for persistent data. Can be dbm or sqlite.
PERSISTENT_DATA_BACKEND = dbm

# Debug application (yes/no): Debugging info in compilation,
# JavaScript, ocsigenserver
DEBUG := no

# User to run server with (make run.*)
WWWUSER := www-data
WWWGROUP := www-data

# Port for running the server (make run.*)
PORT := 80

# Port for testing (make test.*)
TEST_PORT := 8080

# Root of installation (must end with /)
PREFIX := /usr/local/

# Local folder for make test.* (must end with /)
TEST_PREFIX := local/

# The installation tree (relative to $(PREFIX) when
# installing/running or $(TEST_PREFIX) when testing).
# Configuration file $(PROJECT_NAME).conf
ETCDIR := etc/${PROJECT_NAME}
# Project's library $(PROJECT_NAME).cma (cmxs)
LIBDIR := lib/${PROJECT_NAME}
# Command pipe, eg. $ echo reload > $(INSTALL_PREFIX)$(CMDPIPE)
CMDPIPE := var/run/${PROJECT_NAME}-cmd
# Ocsigenserver's logging files
LOGDIR := var/log/${PROJECT_NAME}
# Ocsigenserver's persistent data files
DATADIR := var/data/${PROJECT_NAME}
# Copy of $(LOCAL_STATIC)
STATICDIR := var/www/${PROJECT_NAME}/static
# Project's JavaScript file
ELIOMSTATICDIR := var/www/${PROJECT_NAME}/eliom
